server.port=8000
spring.datasource.url=jdbc:postgresql://localhost:5432/Curious-Sync
spring.datasource.username=postgres
spring.datasource.password=Admin@1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# for coloring the console output
spring.output.ansi.enabled=always