spring.config.import=optional:file:.env[.properties]

server.port=${SERVER_PORT}

# database configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# for coloring the console output
spring.output.ansi.enabled=always

# redis configuration
spring.data.redis.host=${REDIS_CLOUD_PUBLIC_ENDPOINT}
spring.data.redis.port=${REDIS_CLOUD_PORT}
spring.data.redis.password=${REDIS_CLOUD_PASSWORD}

# kafka configuration
kafka.bootstrap-servers=localhost:9092

# kafka logging configuration
logging.level.org.apache.kafka=ERROR
logging.level.org.springframework.kafka=ERROR
logging.level.org.apache.kafka.clients.consumer.ConsumerConfig=ERROR
logging.level.org.apache.kafka.clients.producer.ProducerConfig=ERROR