spring.config.import=optional:file:.env[.properties]

server.port=${SERVER_PORT}

# database configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ScyllaDB configuration
spring.cassandra.contact-points=127.0.0.1
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.keyspace-name=dev_sandbox
spring.cassandra.port=9042
spring.cassandra.schema-action=none

# for coloring the console output
spring.output.ansi.enabled=always

# redis configuration
spring.data.redis.host=${REDIS_CLOUD_PUBLIC_ENDPOINT}
spring.data.redis.port=${REDIS_CLOUD_PORT}
spring.data.redis.password=${REDIS_CLOUD_PASSWORD}

# kafka configuration
kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
kafka.consumer.max-poll-records=10000
kafka.consumer.fetch-min-bytes=10485760
kafka.consumer.fetch-max-wait-ms=2000

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# kafka logging configuration
logging.level.org.apache.kafka=ERROR
logging.level.org.springframework.kafka=ERROR
logging.level.org.apache.kafka.clients.consumer.ConsumerConfig=ERROR
logging.level.org.apache.kafka.clients.producer.ProducerConfig=ERROR

# HikariCP connection pool
spring.datasource.hikari.maximum-pool-size=40

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true